In [1]:
pip install numpy pandas scikit-learn

Requirement already satisfied: numpy in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.4)
Requirement already satisfied: pandas in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.2)
Requirement already satisfied: scikit-learn in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Sanjit\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\Sanjit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\Sanjit\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [ ]:
train_data = pd.read_csv("dataset/titanic/train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
test_data = pd.read_csv("dataset/titanic/test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
# data of women
women = train_data.loc[train_data.Sex == 'female']

# survived column of women
women_survived = women['Survived']

# rate of survival within women
# adding the ones in the column = total survivors
# total number of rows =  total women
women_survival_rate = sum(women_survived)/len(women_survived)

In [ ]:
men_survived = train_data.loc[train_data.Sex=='male']['Survived']
men_survival_rate = sum(men_survived)/len(men_survived)

In [7]:
print("women survival rate:", women_survival_rate)
print("men survival rate:", men_survival_rate)

women survival rate: 0.7420382165605095
men survival rate: 0.18890814558058924

titles

In [8]:
def substrings_in_string(big_string, substrings):
    # nan value is float type
    if isinstance(big_string, float):
        return np.nan
    for substring in substrings:
        if big_string.find(substring) != -1:
            return substring
    print(big_string)
    return np.nan

In [ ]:
title_list=['Mrs', 'Mr', 'Master', 'Miss', 'Major', 'Rev', 'Dr', 'Ms', 'Mlle', 'Col', 'Capt', 'Mme', 'Countess', 'Don', 'Jonkheer']
train_data['Title'] = train_data['Name'].map(lambda x: substrings_in_string(x, title_list))

def replace_titles(x):
    title = x['Title']
    if title in ['Don', 'Major', 'Capt', 'Jonkheer', 'Rev', 'Col']:
        return 'Mr'
    elif title in ['Countess', 'Mme']:
        return 'Mrs'
    elif title in ['Mlle', 'Ms']:
        return 'Miss'
    else:
        return title
    
train_data['Title'] = train_data.apply(replace_titles, axis=1)

deck

In [ ]:
cabin_list = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T', 'Unknown']

train_data['Deck'] = train_data['Cabin'].map(lambda x: substrings_in_string(x, cabin_list))

family size

In [ ]:
train_data['Family_Size'] = train_data['SibSp'] + train_data['Parch']

Age*Class

In [ ]:
train_data['Age*Class']=train_data['Age']*train_data['Pclass']

fare per person

In [ ]:
train_data['Fare_Per_Person'] = train_data['Fare']/(train_data['SibSp']+train_data['Parch']+1)

**gender seems to be strong indicator of survival**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

y_train = train_data['Survived']
# y_test = test_data['Survived']

features = ['Pclass', 'Sex', 'SibSp', 'Parch']
X_train = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': y_pred})
output.to_csv('submission.csv', index=False)
print("submission saved")

submission saved

accuracy cant work because we dont have y_test

In [ ]:
# from sklearn.metrics import accuracy_score, classification_report

# accuracy = accuracy_score(y_test, y_pred)
# classification_rep = classification_report(y_test, y_pred)

# print(f"Accuracy: {accuracy:.2f}")
# print("\nClassification Report:\n", classification_rep)

ValueError: Found input variables with inconsistent numbers of samples: [891, 418]